apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: security-prod

resources:
  - ../../base

patches:
  - path: patches/deployment-patch.yaml
    target:
      kind: Deployment
      name: security-service

configMapGenerator:
  - name: security-service-config
    behavior: merge
    literals:
      - SPRING_PROFILES_ACTIVE=prod
