apiVersion: v1
kind: Secret
metadata:
  name: security-service-secrets
  labels:
    app: security-service
type: Opaque
stringData:
  JWT_SECRET: "REPLACE_WITH_ACTUAL_SECRET"
  LDAP_MANAGER_DN: "REPLACE_WITH_ACTUAL_DN"
  LDAP_MANAGER_PASSWORD: "REPLACE_WITH_ACTUAL_PASSWORD"
  REDIS_PASSWORD: "REPLACE_WITH_ACTUAL_PASSWORD"
